
service: scr

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.10

functions:
  rate:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  crone:
    handler: handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/2 * ? * MON-SAT *)

plugins:
  - serverless-pydeps
